title: Ultracrepidarians
description: A compendium of musings from profound (and pretentious) individuals.

plugins:
  - jekyll-feed
  
permalink: /:collection/:year-:month-:day-:title:output_ext

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
